---
- name: Download Atom editor
  get_url:
    url: https://atom.io/download/deb
    dest: /tmp/atom.deb

- name: Install Atom editor
  apt:
    deb: /tmp/atom.deb
  become: true

- name: Install base packages
  apt:
    name: "{{item}}"
    state: present
  become: true
  with_items:
    - python-pip
    - python-dev
    - build-essential
    - python3
    - nodejs
    - nodejs-legacy
    - npm
