---
- name: Install base packages
  package:
    name: "{{item}}"
    state: present
  become: true
  with_items:
    - gpg
    - python-pip
    - python3
    - mongodb
    - mongodb-server
    - zsh
