---
- include_tasks: install_osx.yml
  when: ansible_distribution == "MacOSX"

- include_tasks: install_linux.yml
  when: ansible_distribution != "MacOSX"

- name: Install ganache and truffle
  npm: name="{{item}}" global=yes
  become: true
  with_items:
    - ganache-cli
    - truffle
