---
- homebrew_tap:
    name: ethereum/ethereum
    state: present

- name: Install geth client
  package:
    name: "{{item}}"
    state: present
  become: "{{package_user}}"
  with_items:
    - ethereum
