---
- name: Download geth
  get_url:
    url: https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.7.3-4bb3c89d.tar.gz
    dest: /tmp/geth.tar.gz

- name: Extract geth
  unarchive:
    src: /tmp/geth.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy geth binary
  copy:
    src: /tmp/geth-linux-amd64-1.7.3-4bb3c89d/geth
    dest: /usr/local/bin/geth
    mode: 0755
  become: true
