- hosts: localhost
  vars:
    default_shell: "bash"
    nf_user: "icole"
    nf_group: "icole"
    nf_single_fonts:
      - "CascadiaCode/Regular/complete/Caskaydia Cove Nerd Font Complete Regular.otf"
      - "CascadiaCode/Regular/complete/Caskaydia Cove Nerd Font Complete Mono Regular.otf"
      - "Overpass/Non-Mono/Regular/complete/Overpass Regular Nerd Font Complete.otf"
      - "Overpass/Mono/Regular/complete/Overpass Mono Regular Nerd Font Complete Mono.otf"
      - "JetBrainsMono/Ligatures/Regular/complete/JetBrains Mono Regular Nerd Font Complete.ttf"
      - "JetBrainsMono/Ligatures/Regular/complete/JetBrains Mono Regular Nerd Font Complete Mono.ttf"
  roles:
    - base
  tasks:
    - include: tasks/zsh.yml
