---
- name: Install Signal COPR repository
  command:
    cmd: dnf copr enable -y luminoso/Signal-Desktop
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:luminoso:Signal-Desktop.repo
  when: ansible_facts['distribution'] == 'Fedora'

- name: Add SUSE OBS repository
  community.general.zypper_repository:
    repo: "https://download.opensuse.org/repositories/network:im:signal/openSUSE_Tumbleweed/"
    name: "Signal"
    auto_import_keys: yes
    state: present
  when: ansible_facts['os_family'] == 'Suse'
