---
- name: Allow RVM GPG key
  shell: gpg2 --keyserver hkp://hydra.opensuse.org --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: Install RVM
  shell: curl -sSL https://get.rvm.io | grep -v __rvm_print_headline | bash -s stable --ruby=ruby --gems=bundler,rake --auto-dotfiles  --user-install
