---
- name: Install Powerline
  package:
    name: "{{ item }}"
  become: "{{ package_user }}"
  with_items:
    - powerline
    - tmux-powerline

- name: Initialize .config directory
  file:
    dest: ~/.config/powerline/themes/tmux
    state: directory

- name: Copy tmux theme
  copy:
    src={{ playbook_dir}}/roles/powerline/files/tmux.json
    dest=~/.config/powerline/themes/tmux/default.json
