---
- name: Install vim
  package:
    name: vim
    state: latest
  become: "{{package_user}}"

- stat: path=~/.vim/
  register: oldvim

- name: Download Janus installer
  get_url:
    url: https://bit.ly/janus-bootstrap
    dest: /tmp/janus-bootstrap
    mode: 0755
  when: oldvim.stat.isdir is not defined

- name: Run Janus installer
  script: /tmp/janus-bootstrap
  when: oldvim.stat.isdir is not defined
