---
- name: Install vim
  package:
    name: vim
    state: latest
  become: "{{package_user}}"

- stat: path=~/.vim/
  register: oldvim

- name: Install Janus
  shell: curl -L https://bit.ly/janus-bootstrap | bash
  when: oldvim.stat.isdir is not defined
